version: '3.8'

services:
  rag_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - RAG_HOST=0.0.0.0
      - RAG_PORT=8000
